### ISSUE TITLE
Issue logging in after using polymorph potion-Bewitchment

### ISSUE THREAD

**Issue by Waaddlleess** [Ladysnake/Impersonate#25]
Within a multiplayer server I attempted to polymorph into someone but immediately crashed the server. The other people can log in but when I attempt to do so it crashes and boots everyone out. 

This is the error from the console:
[03:47:31] [Netty Epoll Server IO #2/ERROR]: Error receiving packet 52 java.lang.IllegalArgumentException: Don't know how to serialize io.github.ladysnake.impersonate.impl.ImpersonateTextContent@5cba4f2e as a Component

Heres the log
https://pastebin.com/KijbYxFV

**Comment by HazardLaser** [comment]
I have sort of the same issue. I don't kick everyone from the server, but I've sort have been banned from my server now. After using the polymorph potion from bewitchment, I disconnected from the server with this error message. " Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Don't know how to serialize io.github.ladysnake.impersonate.impl.ImpersonateTextContent@75b11bae as a Component". 

I can no longer play on the server due to it not letting me connect.

Here is my console log:
[https://pastebin.com/081j1gmU](https://pastebin.com/081j1gmU)

**Comment by Pyrofab** [comment]
Thanks for the report ! Should be fixed in next release.

**Comment by jaredniegas** [comment]
If you haven't solved the problem, you can fix it by deleting your ActiveEffects using an NBT editor. :)
