### ISSUE TITLE
Player data doesn't save when you relog if you impersonate someone

### ISSUE THREAD

**Issue by CammiePone** [Ladysnake/Impersonate#4]
**Minecraft Version:**
1.16.4

**Impersonate Version:**
2.0.3

**Mods:**
Impersonate
Fabric API

**What happens:**

Starting position and skin
![image](https://user-images.githubusercontent.com/16853086/103237862-f694ff00-4916-11eb-83ee-9863a75a9d44.png)

Logged out here disguised as friend
![image](https://user-images.githubusercontent.com/16853086/103237942-352ab980-4917-11eb-97d7-0bed44966a60.png)

Relogged aaaand... it put me where I spawned originally because I never logged out when I did the impersonate command
![image](https://user-images.githubusercontent.com/16853086/103237960-4247a880-4917-11eb-9a20-0391fba43a17.png)

**Comment by Pyrofab** [comment]
Wow that's a really weird bug. Thanks for the detailed report !

**Comment by CammiePone** [comment]
I should also mention that if you put items in your inventory, relog, then disguise yourself, throw the items on the ground, and relog again, the items will be in both your inventory and on the ground, allowing for duping.

**Comment by Aelpecyem** [comment]
This is caused by entity data saving relying on the system name of the entity
This is changed [here](https://github.com/Ladysnake/Impersonate/blob/6d55b825d0b0b94e6493a3142acaf8e13418d291/src/main/java/io/github/ladysnake/impersonate/impl/mixin/PlayerEntityMixin.java#L80-L87), I'll try adding a mixin to fix this
